server:
  port: 8000

spring:
  application:
    name: commerce-gateway
  cloud:
    gateway:
      routes:

        - id: commerce-auth
          uri: ${AUTH_DEFAULT_URL}
          predicates:
            - Path=/v1/auth/**

        - id: commerce-user
          uri: ${USER_DEFAULT_URL}
          predicates:
            - Path=/v1/users/**
          filters:
            - CustomAuthFilter
            - RewritePath=/v1/products/(?<path>.*),/$\{path}

        - id: commerce-product
          uri: ${PRODUCT_DEFAULT_URL}
          predicates:
            - Path=/v1/products/**
          filters:
            - CustomAuthFilter
            - RewritePath=/v1/products/(?<path>.*),/$\{path}

        - id: commerce-order
          uri: ${ORDER_DEFAULT_URL}
          predicates:
            - Path=/v1/orders/**
          filters:
            - CustomAuthFilter
            - RewritePath=/v1/products/(?<path>.*),/$\{path}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${EUREKA_HOST}

logging:
  level:
    root: debug
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"