server:
  port: 8888

spring:
  application:
    name: commerce-auth

  redis:
    host: localhost
    port: ${REDIS_PORT}

  jwt:
    secret: ${SECRET_KEY}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${EUREKA_HOST}

feign:
  commerce-user:
    url: http://localhost:8081/v1/users

logging:
  level:
    root: debug
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
