server:
  port: 8888

spring:
  application:
    name: commerce-auth

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/auth?autoReconnect=true&serverTimezone=Asia/Seoul&characterEncoding=utf8&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    database: mysql
  flyway:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/auth?autoReconnect=true&serverTimezone=Asia/Seoul&characterEncoding=utf8&useSSL=false
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    sql-migration-suffixes: sql
    baseline-on-migrate: true
    baseline-version: 0
    encoding: UTF-8
    locations: classpath:/db/migration

  jwt:
    secret: ${SECRET_KEY}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${EUREKA_HOST}

feign:
  commerce-user:
    url: http://localhost:8081/v1/users
