name: commerce-github-action CI

on:
  push:
    branches:
      - 'feature/*'
      - 'develop'
  workflow_dispatch:
  
  pull_request:
    branches:
      - 'feature/*'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
        
